const mongoose = require("mongoose");

const promoCodeSchema = new mongoose.Schema(
  {
    code: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
    },

    // Type of promo code
    promoType: {
      type: String,
      enum: ["company", "influencer"],
      default: "company",
    },

    discountType: {
      type: String,
      enum: ["percentage", "fixed"],
      required: true,
    },

    discountValue: {
      type: Number,
      required: true,
      min: 0,
    },

    minOrderAmount: {
      type: Number,
      default: 0,
    },

    maxDiscount: {
      type: Number,
      default: null, // For percentage discounts, cap the max discount
    },

    usageLimit: {
      type: Number,
      default: null, // null = unlimited
    },

    usedCount: {
      type: Number,
      default: 0,
    },

    validFrom: {
      type: Date,
      default: Date.now,
    },

    validUntil: {
      type: Date,
      required: true,
    },

    isActive: {
      type: Boolean,
      default: true,
    },

    description: {
      type: String,
      default: "",
    },

    // For influencer promos - earning per unit sold
    earningPerUnit: {
      type: Number,
      default: 5, // ₹5 per unit
    },

    // Total earnings generated by this promo
    totalEarnings: {
      type: Number,
      default: 0,
    },

    // Total units sold through this promo
    totalUnitsSold: {
      type: Number,
      default: 0,
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null, // Admin/Influencer who created this promo
    },

    // Track promo usage history
    usageHistory: [
      {
        userId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        orderId: { type: mongoose.Schema.Types.ObjectId, ref: "Order" },
        discountApplied: Number,
        unitsSold: Number,
        earningGenerated: Number,
        usedAt: { type: Date, default: Date.now },
      },
    ],
  },
  { timestamps: true }
);

// Index for quick lookups
promoCodeSchema.index({ code: 1, isActive: 1 });

module.exports = mongoose.model("PromoCode", promoCodeSchema);
